esphome:
  name: bedroom_remote
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
light:
  - platform: rgb
    name: "Ambient"
    red: gpio_25
    green: gpio_26
    blue: gpio_27
    effects:
      - random:

output:
  - platform: ledc
    pin: GPIO25
    id: gpio_25
  - platform: ledc
    pin: GPIO26
    id: gpio_26
  - platform: ledc
    pin: GPIO27
    id: gpio_27
